apiVersion: v1
data:
  grafana.ini: |
    [auth]
    disable_login_form = false
    disable_signout_menu = false
    [auth.basic]
    enabled = true
    [paths]
    data = /var/lib/grafana
    logs = /var/lib/grafana/logs
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [security]
    cookie_secure = true
    [server]
    http_addr = 0.0.0.0
    http_port = 3000
kind: ConfigMap
metadata:
  name: grafana-custom
  namespace: openshift-monitoring
