apiVersion: v1
kind: Service
metadata:
  name: grafana-custom
  namespace: openshift-monitoring
spec:
  ports:
  - name: https
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana-custom
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
